name: AIPU-Build-And-Test

on:
  push:
    branches: [ "triton_v3.3.x" ]
  pull_request:
    branches: [ "triton_v3.3.x" ]

jobs:
  aipu-build-and-test:
    uses: flagos-ai/flagtree/.github/workflows/aipu-build-and-test.yml@main
