name: Ascend-Build-And-Test

on:
  push:
    branches: [ "triton_v3.2.x" ]
  pull_request:
    branches: [ "triton_v3.2.x" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ascend-build-and-test:
    runs-on: ascend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: FlagTree Build on Ascend
        shell: bash
        run: |
          export FLAGTREE_BACKEND=ascend
          source ~/env.sh
          cd python
          MAX_JOBS=32 python3 -m pip install . --no-build-isolation

      - name: FlagTree Test on Ascend
        shell: bash
        run: |
          source /usr/local/Ascend/ascend-toolkit/set_env.sh
          python3 third_party/tests/ascend/vector-add.py
