name: Ascend-Build-And-Test

on:
  push:
    branches: [ "triton_v3.2.x" ]
  pull_request:
    branches: [ "triton_v3.2.x" ]

jobs:
  ascend-build-and-test:
    uses: flagos-ai/flagtree/.github/workflows/ascend-build-and-test.yml@main
