name: NV-Build-And-Test

on:
  schedule:
    - cron: '0 21 * * *'
  push:
    branches: [ "main", "triton_v3.2.x", "triton_v3.3.x", "triton_v3.4.x", "triton_v3.5.x" ]
  pull_request:
    branches: [ "main", "triton_v3.2.x", "triton_v3.3.x", "triton_v3.4.x", "triton_v3.5.x" ]

jobs:
  nv-build-and-test:
    uses: flagos-ai/flagtree/.github/workflows/nv-build-and-test.yml@main
